name: IceEddie
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyter
  - matplotlib-base>=2.0.2
  - netcdf4>=1.1.9
  - numpy>=1.9.1
  - scipy>=0.16.0
  - xarray>=0.10.8
  - cftime>=1.6.2
  - f90nml>=1.4.4
  - pandas>=2.1.1 
  - bottleneck
  - pip:
    - suncalc>=0.1.3

  # Testing
  - pytest
