# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: test-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Copy namoptions for this test
        run: cp AWS14_namoptions namoptions 
        
      - name: Run IceEddie script
        shell: bash -el {0}
        run: |
          python IceEddie.py
      
      - name: Check if L1B folder is not empty
        run: |
          if [ -z "$(ls -A ANT/AWS14/L1B/)" ]; then
            echo "L1B folder is empty!"
            exit 1
          else
            echo "L1B folder contains files."
          fi